language: csharp
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
before_script:
  - chmod +x build.sh
script:
  - ./build.sh
notifications:
  email:
    - chocolatey-build-status@googlegroups.com
