language: csharp
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
before_script:
  - chmod +x build.sh
script:
  - ./build.sh
notifications:
  email:
    - chocolatey-build-status@googlegroups.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bd7909ec077be3f8873e
    on_success: change  
    on_failure: always  
    on_start: false     
